name: New Features
description: Features to improve the system
body:
  - type: textarea
    attributes:
      label: What is this feature about?
      description: Explain what is needed to enhance
    validations:
      required: true
  - type: textarea
    attributes:
      value: |
          - [ ] Task
          - [ ] Task
      label: What are the steps to do the feature?
      description: List all needed tasks to be done for this feature
    validations:
      required: true
